const config = {};
// 本地dev开发模拟用户信息
config.userTest = {
  // 模拟获取的用户uid
  uid: 'test01',
  isLocal: true,
  // 模拟token，在这里写入
  accessToken: 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJaT2lnME13TnVHRHBHTXZoWmpEemExbU9ONGlzSGVSRlJzMjVfSjdQYWlBIn0.eyJleHAiOjE2MTY4NzMzNTgsImlhdCI6MTYxNjg1MTc1OCwianRpIjoiYmEzZjI2MmEtMGZkYi00Y2NhLTliMDMtZWNlNmRhNTNlOGQ1IiwiaXNzIjoiaHR0cDovL2d6YmluLmNvbS5jbi9hdXRoL3JlYWxtcy9tYWluIiwiYXVkIjpbInJlYWxtLW1hbmFnZW1lbnQiLCJvYS1zZXJ2aWNlIiwiYWNjb3VudCJdLCJzdWIiOiJlY2JhMDI1Zi0wNDY2LTRkZWEtYmI2ZS0xZTk3NDg0MDg3OTUiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJpYWkuYmllYXJuLmNvbSIsInNlc3Npb25fc3RhdGUiOiI2ZDBhZTBhOS1lYmI5LTQ4MTMtYmU4YS1jZDkyMGZhMzQ2MzEiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiTWF0ZXJpYWxfUiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJ2aWV3LXJlYWxtIiwidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwiaW1wZXJzb25hdGlvbiIsInJlYWxtLWFkbWluIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJvYS1zZXJ2aWNlIjp7InJvbGVzIjpbIk1hdGVyaWFsX1IiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfSwiaWFpLmJpZWFybi5jb20iOnsicm9sZXMiOlsiTWF0ZXJpYWxfUiJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6Ikthc3NpYSBaaGVuZyIsInByZWZlcnJlZF91c2VybmFtZSI6Imthc3NpYSIsImdpdmVuX25hbWUiOiJLYXNzaWEiLCJmYW1pbHlfbmFtZSI6IlpoZW5nIiwiZW1haWwiOiJhYWEifQ.gXhqBUwnnITSn8VutYNQFwiAPPXjNjuNTinLRvvo51dsSGuUAJrmIfhHISl5T-ZxcIaXVUUYQ6JEhQ8auNLuQ0QixAgjV5onU5EDb3iFwcXP8_RiMGHgRJ4CsjNvbT7gv9ZQ8MhI97bYVNzEcVPdPH5lM0t8TSdBhnYTxruMyuBZjGLytm6A5Y643ZWI0-wJPmpPVQkZG7cOQT-kakeRJXi829CVG8z0WeDZiVILLvrdgSkGnxNw6YNdgDG4ZwatmqqbxS89FfqOyb63eoMWo_4I8OCCShb8pOHjRxKUuH8Jf1s15Pq2w_LCMwtEfKEKfKStqwSVxaukuRdoP3Q9dA',
};
// config.statusBarColor = [72, 71, 89, 1]; // 状态栏颜色
config.language = 'CN'; // 状态栏颜色 'CN,EN'

// 配置devServer代理url
config.baseUrl = {
  // 开发环境
  local: 'http://gzbin.com.cn/',
  // 生产环境
  product: 'http://8.134.14.195/',
};

module.exports = config;
